### ISSUE TITLE
`substreams.yaml` examples for other networks

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams-erc20-balance-changes#3]
Would it be possible to provide additional `substreams.yaml` examples with other networks using:
- `network`
- `deriveFrom`
- `initialBlock` (different per network)

Additionally to publish as *.spkg as releases

## Network examples
- `substreams.yaml` (no initialBlock, no network)
- `substreams.mainnet.yaml` (initialBlock: 1397553)
- `substreams.polygon.yaml` (initialBlock: 2764)
- `substreams.bnb.yaml` (initialBlock: 64253)

## Example

`substreams.polygon.yaml`

```yaml
deriveFrom: https://github.com/streamingfast/substreams-erc20-balance-changes/releases/download/v1.1.0/erc20-balance-changes-v1.1.0.spkg

package:
  name: "erc20-balance-changes.polygon"
  version: "1.1.0"

network: polygon

initialBlocks:
  map_balance_changes: 2764
  map_valid_balance_changes: 2764
  map_unknown_balance_changes: 2764
  graph_out: 2764
```
